# Generated by Django 3.0.7 on 2021-05-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Numero', models.CharField(max_length=10)),
                ('Intentos', models.CharField(max_length=10)),
            ],
        ),
    ]
